CREATE TABLE IF NOT EXISTS listings (id TEXT PRIMARY KEY, data TEXT);
CREATE TABLE IF NOT EXISTS gaushalas (id TEXT PRIMARY KEY, data TEXT);
CREATE TABLE IF NOT EXISTS alerts (id TEXT PRIMARY KEY, data TEXT);
CREATE TABLE IF NOT EXISTS transports (id TEXT PRIMARY KEY, data TEXT);
CREATE TABLE IF NOT EXISTS vets (id TEXT PRIMARY KEY, data TEXT);
CREATE TABLE IF NOT EXISTS sponsorships (id TEXT PRIMARY KEY, data TEXT);
